spring:
  profiles:
    active: local
  config:
    import: myDatabaseInfo.yml, oauth2.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#logging
#deeping LV : 1.ERROR 2.WARN 3.INFO 4.DEBUG. 5.TRACE
logging:
  level:
    com:
      deeping: WARN
  file:
    name: log/developer.log


