spring:
  mail:
    username: everycampingshop@gmail.com
    password: ENC(uvepi/z4e7XQ0Y9ipf0uXKx0qcTPET2PkzO24zTyHJs=)
  jpa:
    hibernate:
      ddl-auto: update

aws:
  s3:
    bucketname: everycamping
    endpointurl: https://everycamping.s3.ap-northeast-2.amazonaws.com
    accesskey: ENC(vEMCqnn8y1/EDxOh+dltN2rVZZ5QK1QhW2iPgkFZw2g=)
    secretkey: ENC(ESfQCT5E4gH5acKw0VOHs5f0iR15406HwGgf1WcfrqNq4oUHVWQeSrIOvbZf3NbkQ27XKZRiBDM=)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: root
    password: 1
    url: jdbc:mariadb://localhost:3306/everycamping
  redis:
    host: localhost
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: admin
    password: ENC(EZ8FmMfnQZDF5Buyzvqhcuhxzy6Imlsy)
    url: jdbc:mariadb://everycamping-rds.cklf3l4rcuqo.ap-northeast-2.rds.amazonaws.com:3306/everycamping
  redis:
    host: ec2-43-200-2-48.ap-northeast-2.compute.amazonaws.com
