spring:
  mail:
    username: everycampingshop@gmail.com
    password: bwrlboxfgoouwubf
  jpa:
    hibernate:
      ddl-auto: update

aws:
  s3:
    bucketname: everycamping
    endpointurl: https://everycamping.s3.ap-northeast-2.amazonaws.com
    accesskey: AKIAUDUI3F6FN3ZDITHI
    secretkey: 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

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: root
    password: 1
    url: jdbc:mariadb://localhost:3306/everycamping
  redis:
    host: localhost
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password: "1"
    url: jdbc:mariadb://ec2-43-200-2-48.ap-northeast-2.compute.amazonaws.com:3306/everycamping
  redis:
    host: ec2-43-200-2-48.ap-northeast-2.compute.amazonaws.com
