spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: everycamping_local
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: 6a63133c53698e10384dd44303eb211f
            client-secret: XA8vIC09HMgrW3qH7ORQkW5QBF3chJd7

---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: everycamping
            redirect-uri: https://everycamping.netlify.app/kakaoLoginCallback
            client-id: be983b429f1e7b89c3832b7738ae7875
            client-secret: qAXDzUbaRBRrb6tLCGRpSLUszxrbE2fK

